// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eekxczdsxmysszprqzeg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVla3hjemRzeG15c3N6cHJxemVnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyMzQwNzUsImV4cCI6MjA3MDgxMDA3NX0.kTYW-jJt6I0jNItLwOHBV-zrOdUV1Gr_7V0I4thr-Hw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});